# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('custom-applications', ['core', 'utils', 'applications', 'p4-switch'])
    module.source = [
        'model/custom-applications.cc',
        'model/custom-onoff-application.cc',
        'model/rate-send-application.cc',
        'model/trace-send-application.cc',
        'model/raw-send-application.cc',
        'model/simple-send.cc',
        'model/custom-bulk-application.cc',
        'helper/custom-bulk-helper.cc',
        'helper/custom-applications-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('custom-applications')
    module_test.source = [
        'test/custom-applications-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'custom-applications'
    headers.source = [
        'model/custom-applications.h',
        'model/simple-send.h',
        'model/rate-send-application.h',
        'model/trace-send-application.h',
        'model/raw-send-application.h',
        'helper/custom-bulk-helper.h',
        'model/custom-onoff-application.h',
        'model/custom-bulk-application.h',
        'helper/custom-applications-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

